twig:
    file_name_pattern: '*.twig'
    strict_variables: true
    paths:
        'src/Admin/templates': Admin
        'src/App/templates': App
    form_theme:
        - 'bootstrap_5_layout.html.twig'
