version: '3'

services:
  database:
    image: mysql:8.0.36
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sftraining
      - MYSQL_USER=sftraining
      - MYSQL_PASSWORD=123456
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "9101:3306"
